---
pipeline:
  name: MyPipeline
  roleArn: arn:aws:iam::141341433137:role/CodePipelineRole 
  artifactStore:
    type: S3
    location: cloudtecdev-codepipeline-artifacts
  stages:
    - name: Source
      actions:
        - name: Source
          actionTypeId:
            category: Source
            owner: ThirdParty
            provider: GitHub
            version: 1
          outputArtifacts:
            - name: SourceArtifact
          configuration:
            Owner: dlobe
            Repo: <repository-name>
            Branch: main
            OAuthToken: <oauth-token>
          runOrder: 1
    - name: Build
      actions:
        - name: Build
          actionTypeId:
            category: Build
            owner: AWS
            provider: CodeBuild
            version: 1
          inputArtifacts:
            - name: SourceArtifact
          outputArtifacts:
            - name: BuildArtifact
          configuration:
            ProjectName: <codebuild-project-name>
          runOrder: 1
    - name: Deploy
      actions:
        - name: Deploy
          actionTypeId:
            category: Deploy
            owner: AWS
            provider: CloudFormation
            version: 1
          inputArtifacts:
            - name: BuildArtifact
          configuration:
            ActionMode: CHANGE_SET_REPLACE
            StackName: my-stack
            Capabilities: CAPABILITY_NAMED_IAM
            TemplatePath: BuildArtifact::template.yaml
          runOrder: 1
